prefixes:
- code: TBD
  last_index: '7'
- code: 01_P-PO
  last_index: 6
- code: 02_P-PPA
  last_index: 7
- code: 03_P-POP
  last_index: 8
- code: 04_P-CFF
  last_index: 13
- code: 04_P-COA
  last_index: 18
- code: 04_P-MBZ
  last_index: 11
- code: 04_P-POV
  last_index: null
- code: TBDa
  last_index: 2
last_scan:
  prefix: TBD
  folder: C:\Users\Wally
  filename: TBD_7_A
options:
  scanner:
    naps2_path: C:\Program Files\NAPS2\NAPS2.Console.exe
    driver: wia
    device: lide
    dpi: 600
    filetype: png
