prefixes:
- code: TBD
  last_index: '37'
- code: 01_P-PO
  last_index: 6
- code: 02_P-PPA
  last_index: 7
- code: 03_P-POP
  last_index: '1'
- code: 04_P-CFF
  last_index: 13
- code: 04_P-COA
  last_index: 18
- code: 04_P-MBZ
  last_index: 11
- code: 04_P-POV
  last_index: null
last_scan:
  prefix: TBD
  folder: D:\Desktop
  filename: TBD_37_A
options:
  scanner:
    naps2_path: C:\Program Files\NAPS2\NAPS2.Console.exe
    driver: twain
    device: twain
    dpi: 600
    filetype: png
