prefixes:
- code: 00_TBD
  last_index: 19
last_scan:
  prefix: 00_TBD
  folder: null
  filename: 00_TBD_18_B
options:
  scanner:
    naps2_path: C:\Program Files\NAPS2\NAPS2.Console.exe
    driver: twain
    device: twain
    dpi: 600
    filetype: png
multi_scan:
  folder: null
