FONT_DEFAULT_FAMILY = "Segoe UI"
FONT_DEFAULT_SIZE = 11

FONT_DEFAULT = (FONT_DEFAULT_FAMILY, FONT_DEFAULT_SIZE)
FONT_BIG = (FONT_DEFAULT_FAMILY, 16)
FONT_MEDIUM = (FONT_DEFAULT_FAMILY, 13)

MAP_PLUS_BUTTON = (FONT_DEFAULT_FAMILY, 18)
FONT_DEFAULT_BOLD=(FONT_DEFAULT_FAMILY, 11, "bold")

